- src/components/Projects/EditDeck.vue
- src/generated/graphql.ts
- src/graphql/Projects.graphql
Fix variable name. Update schema and types.
Type mutation variables.
fix #15
> fix: GraphQL Package Update Mutation broken

- src/components/Projects/DeleteProject.vue
- src/views/Projects/ProjectDetail.vue
> fix: Delete not working in ProjectDetail.vue

- package.json
Fixes typo in package.json for auto-changelog configuration.
> fix: auto-changelog config

- schema.graphql
- src/components/Projects/EditDeck.vue
- src/components/mixins.ts
- src/generated/graphql.ts
- src/graphql/Projects.graphql
- src/locales/de.json
- src/locales/en.json
- src/router/index.ts
- src/views/Projects/ProjectDetail.vue
- src/views/Projects/ProjectDetail/ClusterSettings.vue
- src/views/Projects/ProjectDetail/ProjectDecks.vue
- src/views/Projects/ProjectDetail/Sops.vue
- src/views/Projects/ProjectForm.vue
> feature: add cluster settings to project form 

- package-lock.json
- package.json
> fix: package name

- src/components/AppBar.vue
- src/i18n.ts
- src/locales/de.json
- src/locales/en.json
- src/main.ts
- src/router/index.ts
Move i18n code into separate file.
Add labels for views.
Use route meta information is AppBar.vue.
Closes #3
> refactor: i18n and view labels

- src/views/Projects/ProjectForm.vue
> fix: show loading spinner when project is saved

- src/components/Projects/DeleteSops.vue
- src/generated/graphql.ts
- src/graphql/Projects.graphql
- src/locales/de.json
- src/locales/en.json
- src/views/Projects/ProjectDetail/Sops.vue
Project was not updated when SOPS were created or updated.
That caused newly added SOPS not to appear, changed SOPS seemed
not to change.
fixes #39
fixes #40
> fix: update project when SOPS are added or updated

- public/index.html
- src/router/index.ts
Add default page title. Change page title based on route meta label.
Closes #42
> feat: change document title based on route

- src/components/Projects/EditDeck.vue
Removes icons from dropdown.
Fix #31
> fix: wrong margin on selects

- src/views/Projects/AddTeamMember.vue
Store variable could possible be null or maybe not accessible.
This caused the organization query to fail.
Fix #48
> fix: bug which caused add members view to fail / add skeletons

- src/components/Navigation.vue
- src/components/Organizations/OrgaDone.vue
> feat: add loading screen to organization creation

- package-lock.json
- package.json
- src/App.vue
- src/store/modules/context.ts
- src/store/modules/errors.ts
- src/store/modules/ui.ts
- vue.config.js
fix #64
Update ws due to security vulnerability.
> frontend-64 Remove vuex-module-decorators

- .github/workflows/cypress.e2e.yml
> save e2e screenshots to artifacts

- schema.graphql
- src/components/Projects/ProjectList.vue
- src/generated/graphql.ts
- src/graphql/Projects.graphql
- src/locales/de.json
- src/locales/en.json
- src/views/Projects/ProjectDetail.vue
- tests/e2e/fixtures/projects/cypressProject.json
- tests/e2e/specs/e2e/projectDetail.spec.js
fix #71
fix #72
Removes other project list in project detail view.
> fix: project displayed in wrong organization

- src/views/Projects/ProjectDetail.vue
Adds permission check for edit and
delete project button in ProjectDetail.vue.
> fix: add permission check

- src/components/Projects/ProjectMemberAvatars.vue
- src/styles/_extension.scss
When a project has more than 3 members
display + X.
Reduce font size for avatar initials.
Closes #80.
> fix: add member count indicator

- src/App.vue
- src/components/icons/TickWhiteBg.vue
- src/plugins/vuetify.ts
> feat: add snackbar tick icon

- src/App.vue
- src/components/Projects/ProjectList.vue
- src/components/icons/ErrorWhiteBg.vue
- src/plugins/vuetify.ts
- src/store/modules/context.ts
- src/typing/index.ts
- src/views/Projects.vue
closes #82 
add error key to SnackbarMessage type
add errorWhiteBg icon
pass error value to current snackbar store commits
conditionally render snackbar based on !!error
> feat: handle errors in snackbar

- src/views/Projects/ProjectDetail.vue
> fix: remove project bar from detail view

- src/components/AppBar.vue
- src/components/Navigation.vue
- src/components/Notifications/ProjectInvite.vue
- src/locales/de.json
- src/locales/en.json
- tests/e2e/specs/e2e/navbar.spec.js
closes #65 & #79 
remove joinOrganization button in navigation
> feat: show invites in notification dropdown

- src/views/Settings/OrganizationRoles.vue
> feat: catch orga member invitation errors, show in snackbar

- src/components/Navigation.vue
> refactor: remove activity page from navigation for now

- src/views/Projects/ProjectForm.vue
> refactor: change default spec repo branch to "main"

- src/components/Projects/ProjectList.vue
> feature: add project link to icon and project title in project list

- README.md
- add table of contents
- restructure sections
- add release/versioning information
Closes #102
> chore: restructure README.md

- README.md
> chore: update README.md test command description

- src/views/Projects/ProjectDetail.vue
> fix: button break for larger screens

- src/components/Projects/ProjectList.vue
> fix: display date when project modified date is not known

- src/components/Projects/ProjectList.vue
> fix: missing status for non-admin users

- README.md
- kindify.js
> docs: add documentation for GraphQL -> TypeScript conversion process

- src/components/Organizations/OrgaDone.vue
- src/locales/de.json
- src/locales/en.json
- src/views/Organizations/CreateOrganization.vue
> fix: organization creation orgaTitle missing

- src/components/Projects/EditDeck.vue
> fix(#212): remove wrong icons

- src/components/Navigation.vue
> chore: update help link

- src/components/Projects/ProjectList.vue
- tests/e2e/specs/e2e/projectDetail.spec.js
> fix: return empty urls while loading projects, refactor project urls

- src/components/Projects/EditDeck.vue
> fix: button spacing

- src/components/Organizations/OrganizationMembers.vue
- src/locales/de.json
- src/locales/en.json
> refactor: remove skip sentence / translations from OrganizationMembers

- package-lock.json
- package.json
- tests/e2e/plugins/index.js
- tests/e2e/support/commands.js
- tests/e2e/support/index.js
> fix: missing code coverage for vuex store

- src/components/Projects/ProjectBar.vue
> fix: search bar for medium screens

- src/styles/_extension.scss
- src/views/Projects.vue
> fix: missing pagination icons

- src/views/Projects/ProjectDetail/ProjectMembers.vue
> fix: do not show "add" button for project members

- src/views/Projects/ProjectDetail/ProjectMembers.vue
> fix: button color

- src/locales/de.json
- src/locales/en.json
- src/views/Projects/ProjectForm.vue
> feat: show hint for access username in project form

- src/components/Projects/ProjectList.vue
> fix: show cli hint for members

- src/components/Projects/ProjectBar.vue
- src/views/Projects.vue
> feat: add last update sorting choices

- src/components/Organizations/OrganizationMembers.vue
- src/components/Organizations/OrganizationTitle.vue
- tests/e2e/specs/e2e/intro.spec.js
> fix: orga create form keyboard events
